// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
// Users
export const GET_USER = "GET_USER";
export const RATINGS_UPDATED = "RATINGS_UPDATED";
export const RATING_UPDATED = "RATING_UPDATED";
export const RATINGS_ADDED = "RATINGS_ADDED";
export const USER_ERROR = "USER_ERROR";
export const GET_USERS = "GET_USERS";
export const CLEAR_USER = "CLEAR_USER";
export const CLEAR_USERS = "CLEAR_USERS";
export const USER_UPDATED = "USER_UPDATED";
export const PASSWORD_RESET = "PASSWORD_RESET";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const FRIEND_REMOVED = "FRIEND_REMOVED";
export const GET_FRIENDS = "GET_FRIENDS";
// Books
export const BOOKS_UPDATED = "BOOKS_UPDATED";
export const RECOMMENDATIONS_UPDATED = "RECOMMENDATIONS_UPDATED";
export const BOOK_ERROR = "BOOK_ERROR";
// Messaging
export const GET_THREADS = "GET_THREADS";
export const GET_THREAD = "GET_THREAD";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const ADD_MESSAGES = "ADD_MESSAGES";
export const NEW_THREAD = "NEW_THREAD";
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const GET_MESSAGES = "GET_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const CLEAR_THREADS = "CLEAR_THREADS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const CLEAR_THREAD = "CLEAR_THREAD";
export const CLEAR_MESSAGING = "CLEAR_MESSAGING";
export const MESSAGE_ERROR = "MESSAGE_ERROR";
// Data
export const RESULTS_UPDATED = "RESULTS_UPDATED";
export const CLEAR_RESULTS = "CLEAR_RESULTS";
