// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
// Users
export const GET_USER = "GET_USER";
export const RATINGS_UPDATED = "RATINGS_UPDATED";
export const RATING_UPDATED = "RATING_UPDATED";
export const RATINGS_ADDED = "RATINGS_ADDED";
export const USER_ERROR = "USER_ERROR";
export const GET_USERS = "GET_USERS";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const CLEAR_USER = "CLEAR_USER";
export const CLEAR_USERS = "CLEAR_USERS";
export const USER_UPDATED = "USER_UPDATED";
export const PASSWORD_RESET = "PASSWORD_RESET";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const FRIEND_REMOVED = "FRIEND_REMOVED";
// Books
export const BOOKS_UPDATED = "BOOKS_UPDATED";
export const RECOMMENDATIONS_UPDATED = "RECOMMENDATIONS_UPDATED";
export const BOOK_ERROR = "BOOK_ERROR";
